[package]
org = "ballerina"
name = "udp"
version = "1.7.2"
authors = ["Ballerina"]
keywords = ["UDP", "datagram", "transport"]
repository = "https://github.com/ballerina-platform/module-ballerina-udp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "udp-native"
version = "1.7.2"
path = "../native/build/libs/udp-native-1.7.2-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/udp-test-utils-1.7.2-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.94.Final"
path = "./lib/netty-handler-4.1.94.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.94.Final"
path = "./lib/netty-buffer-4.1.94.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.94.Final"
path = "./lib/netty-transport-4.1.94.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.94.Final"
path = "./lib/netty-common-4.1.94.Final.jar"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.94.Final"
path = "./lib/netty-resolver-4.1.94.Final.jar"
