[package]
org = "ballerina"
name = "udp"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../udp-native/build/libs/udp-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "udp"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../udp-test-utils/build/libs/udp-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.udp"
scope = "testOnly"
artifactId = "udp"
version = "@project.version@"

[[platform.java11.dependency]]
artifactId = "netty-handler"
version = "@netty.version@"
path = "./lib/netty-handler-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-buffer"
version = "@netty.version@"
path = "./lib/netty-buffer-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-transport"
version = "@netty.version@"
path = "./lib/netty-transport-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-common"
version = "@netty.version@"
path = "./lib/netty-common-@netty.version@.jar"
groupId = "io.netty"

[[platform.java11.dependency]]
artifactId = "netty-resolver"
version = "@netty.version@"
path = "./lib/netty-resolver-@netty.version@.jar"
groupId = "io.netty"
